### ISSUE TITLE
[5.0] annotation

### ISSUE THREAD

**Issue by hustcc** [antvis/component#102]
- [ ] arc 传入的是 center、radius、startAngle、endAngle，只能用于 polar 下面吗？
 - [ ] image 使用 start、end 定位，用户传入那里是 x y width height，确定这样的吧？
 - [ ] line 中的 text.position 处理逻辑是 Controller 中做，还是 Component 中做？

**Comment by simaQ** [comment]
@dxq613 看下

**Comment by dxq613** [comment]
1. arc 目前看来只能在 polar 下支持
2. image 在 G2 层面定位仅支持 start， end，用户可以在不传入 end 的时候在 style 里面设置 width 和 height。 x,y 不允许用户自己传入。
3. line 的 text.position 在 component 层面已经支持。
