### ISSUE TITLE
types 文件申明与接口文档不一致

### ISSUE THREAD

**Issue by imakan** [antvis/component#217]
@antv/g2/lib/interface.d.ts 中的value?: number[]; 与接口文档中的values描述不符，麻烦看下以谁的为主

**Comment by hustcc** [comment]
什么组件的 value？

**Comment by imakan** [comment]
DualAxes组件 legend中的配置，

**Comment by imakan** [comment]
@hustcc  DualAxes组件 legend中的配置，

**Comment by hustcc** [comment]
ContinueLegendCfg.values 配置吗？一般不用配置这个，应该是以 Components 中的定义为准，如果 G2 不是这个，需要在 G2 中修复。
