### ISSUE TITLE
Why Delete Version 0.8.32

### ISSUE THREAD

**Issue by Dezreal** [antvis/component#285]
请问为什么`@antv/component`的0.8.32版本在 npm 仓库里找不到了，而目前最新版本是0.8.28？

* **Link**: https://www.npmjs.com/package/@antv/component

我们部门的产品前端用到了`tooltip`的`customContent`自定义能力，我们在发现0.8.32版本修复了定义`customContent`后`transition`失效的错误[PR#282](https://github.com/antvis/component/pull/282)之后，就立即进行了版本的同步和适配，但是现在0.8.32版本获取不到了，导致线上的`tooltip`又开始卡顿，难以正常使用。

依赖包的不稳定给我们带来了维护上的困难，请问蚂蚁何时重新发布0.8.32或更高版本？

**Comment by Eve-Sama** [comment]
现阶段, 你可以使用`resolutions`关键字来解决.
```json
"resolutions": {
  "@antv/component":"0.8.32-beta.0"
},
```

**Comment by Eve-Sama** [comment]
32版本的方案有可能对现有业务造成一定影响. 这个影响通常是可能存在外边距合并的问题. 因此, 建议使用正常更新的版本就好, 等官方把这个问题修复了, 会发布新的正常版本号. 如果一定要使用32版本, 那么就可以先用`resolutions`锁死先.

**Comment by Dezreal** [comment]
> 32版本的方案有可能对现有业务造成一定影响. 这个影响通常是可能存在外边距合并的问题. 因此, 建议使用正常更新的版本就好, 等官方把这个问题修复了, 会发布新的正常版本号. 如果一定要使用32版本, 那么就可以先用`resolutions`锁死先.

嗯，我也猜到是这个原因了，感谢前夕大佬回复

**Comment by Dezreal** [comment]
希望蚂蚁尽快发布吧，已经看到 beta 版本了

**Comment by Dezreal** [comment]
已经看到 beta 版本了，希望蚂蚁尽快发布吧
 * https://www.npmjs.com/package/@antv/component/v/0.8.32-beta.0
 * https://web.npm.alibaba-inc.com/package/@antv/component/v/0.8.32-beta.0
