### ISSUE TITLE
关于titleOffset的适应问题

### ISSUE THREAD

**Issue by fingerpan** [antvis/component#82]
* **Link**:
* **Platform**:
* **Mini Showcase(like screenshots)**:

关于坐标轴，line 类型 的 titleOffset的几点问题。

1. 由于在 https://github.com/antvis/component/blob/master/src/axis/base.js  92行代码中，给title 中的 offset 设置了默认值。与 https://github.com/antvis/component/blob/master/src/axis/line.js 
中的 renderTitle 函数，107行代码逻辑矛盾，只有手动设置offset 为null 才进入此逻辑。

2. https://github.com/antvis/component/blob/master/src/axis/line.js  中 109 行 `labelsGroup` 为 null，正确属性对象应该为：`labelRenderer`

``` javascript
 const labelRenderer = self.get('labelRenderer');
      if (labelRenderer) {
        const labelLength = self.getMaxLabelWidth(labelRenderer);
        const labelOffset = self.get('label').offset || self.get('_labelOffset');
        titleOffset += labelLength + labelOffset;
  }
```

3. offset相对于轴线的偏移量的灵活性不足。 因为Y轴坐标轴的label数据变大的情况下，预先设置的offset值不满足的情况下会导致遮盖。个人建议：

offset 是否可以考虑是相对于坐标轴label文本的偏移量，如果在label有旋转角度的情况下，根据坐标轴项量 / 旋转角度 / label文本最大宽度 / fontSize等条件 可以计算 label文本的实际宽度。

真心希望尽快修复 1，2问题。等待上线中。。

**Comment by dxq613** [comment]
最初设置这个参数的时候，默认设置固定值确实有问题，应该默认 null。但是考虑到不仅仅只有 line 这一类坐标轴，其他的坐标轴自动计算这个 offset 不那么容易，所以就默认设置了固定值。新的版本中 line 的 title 的 offset 将自动计算，配合自动旋转和自动隐藏的逻辑比较复杂。

**Comment by dxq613** [comment]
1. 的问题暂时没法改，考虑到很多系统在运行，一旦改动，对布局有不小的影响，在新版本 G2  4.0 中体现。
2. labelRender 和 labelGroup 按说应该都会存在
