### ISSUE TITLE
[5.0] line axis title.offset 被修改

### ISSUE THREAD

**Issue by hustcc** [antvis/component#90]
传入的配置（title.offset = 32）：

![image](https://user-images.githubusercontent.com/7856674/68636313-17916980-0536-11ea-8aff-5e51f765f7b9.png)

但是在代码中，会修改掉 title.offset 配置。

> expect(y.component.get('title').offset).toBe(32);

**Comment by dxq613** [comment]
title 的 offset 在直角坐标系下不再允许用户修改了，这个都是根据 label 的位置，额外加几个像素。

或者是默认的 offset: null，如果用户设置了，就不覆盖了，但是 limitLength 就失效了

**Comment by hustcc** [comment]
https://github.com/antvis/component/blob/d8cc169de9ad76cee23c00a7f6dafde99670c87e/src/axis/line.ts#L107-L111
应该就是这个地方修改了吧~

**Comment by hustcc** [comment]
ref: https://github.com/antvis/g2/issues/1622
